services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: MD_Backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - md_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: MD_Frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - md_network

networks:
  md_network:
    driver: bridge
