[project]
name = "deployment-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi==0.115.12",
    "numpy<2",
    "pydantic>=2.11.5",
    "uvicorn[standard]>=0.34.3",
]
